language: java
before_install:
  - sudo add-apt-repository ppa:openjdk-r/ppa -y
  - sudo apt-get update
  - sudo apt-get install -y openjdk-8-jdk
  - sudo update-alternatives --auto java
  - sudo update-alternatives --auto javac
  - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

